// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/pdg-tw/go-monster-hearth-server/config"
	"github.com/pdg-tw/go-monster-hearth-server/internal/interfaces/amqp_rpc"
	"github.com/pdg-tw/go-monster-hearth-server/internal/interfaces/rest/v1/go"
	"github.com/pdg-tw/go-monster-hearth-server/internal/translation/application"
	"github.com/pdg-tw/go-monster-hearth-server/internal/translation/domain/translation/service"
	"github.com/pdg-tw/go-monster-hearth-server/internal/translation/infrastructure/googleapi"
	"github.com/pdg-tw/go-monster-hearth-server/internal/translation/infrastructure/repository"
	"github.com/pdg-tw/go-monster-hearth-server/internal/translation/ports"
	"github.com/pdg-tw/go-monster-hearth-server/pkg/httpserver"
	"github.com/pdg-tw/go-monster-hearth-server/pkg/logger"
	"github.com/pdg-tw/go-monster-hearth-server/pkg/postgres"
	"github.com/pdg-tw/go-monster-hearth-server/pkg/rabbitmq/rmq_rpc/server"
)

// Injectors from wire.go:

func InitializeConfig() *config.Config {
	configConfig := config.NewConfig()
	return configConfig
}

func InitializePostgresConnection() *postgres.Postgres {
	configConfig := config.NewConfig()
	postgresPostgres := postgres.NewOrGetSingleton(configConfig)
	return postgresPostgres
}

func InitializeTranslationRepository() *repository.TranslationRepository {
	configConfig := config.NewConfig()
	postgresPostgres := postgres.NewOrGetSingleton(configConfig)
	translationRepository := repository.New(postgresPostgres)
	return translationRepository
}

func InitializeTranslationWebAPI() *googleapi.GoogleTranslator {
	googleTranslator := googleapi.New()
	return googleTranslator
}

func InitializeTranslationUseCase() *application.TranslationUseCase {
	configConfig := config.NewConfig()
	postgresPostgres := postgres.NewOrGetSingleton(configConfig)
	translationRepository := repository.New(postgresPostgres)
	googleTranslator := googleapi.New()
	translationUseCase := application.NewWithDependencies(translationRepository, googleTranslator)
	return translationUseCase
}

func InitializeLogger() *logger.Logger {
	configConfig := config.NewConfig()
	loggerLogger := logger.New(configConfig)
	return loggerLogger
}

func InitializeNewRmqRpcServer() *server.Server {
	configConfig := config.NewConfig()
	loggerLogger := logger.New(configConfig)
	postgresPostgres := postgres.NewOrGetSingleton(configConfig)
	translationRepository := repository.New(postgresPostgres)
	googleTranslator := googleapi.New()
	translationUseCase := application.NewWithDependencies(translationRepository, googleTranslator)
	v := amqprpc.NewRouter(translationUseCase)
	serverServer := server.New(configConfig, loggerLogger, v)
	return serverServer
}

func InitializeNewRmqRpcServerForTesting(config2 *config.Config, translationRepository ports.TranslationRepository, translator service.Translator) *server.Server {
	loggerLogger := logger.New(config2)
	translationUseCase := application.NewWithDependencies(translationRepository, translator)
	v := amqprpc.NewRouter(translationUseCase)
	serverServer := server.New(config2, loggerLogger, v)
	return serverServer
}

func InitializeNewHttpServerForTesting(config2 *config.Config, translationRepository ports.TranslationRepository, translator service.Translator) *httpserver.Server {
	translationUseCase := application.NewWithDependencies(translationRepository, translator)
	loggerLogger := logger.New(config2)
	openapiTranslator := openapi.NewTranslator(translationUseCase, loggerLogger)
	engine := openapi.NewRouter(openapiTranslator)
	httpserverServer := httpserver.New(config2, engine)
	return httpserverServer
}

func InitializeNewTranslator() *openapi.Translator {
	configConfig := config.NewConfig()
	postgresPostgres := postgres.NewOrGetSingleton(configConfig)
	translationRepository := repository.New(postgresPostgres)
	googleTranslator := googleapi.New()
	translationUseCase := application.NewWithDependencies(translationRepository, googleTranslator)
	loggerLogger := logger.New(configConfig)
	translator := openapi.NewTranslator(translationUseCase, loggerLogger)
	return translator
}

func InitializeNewRouter() *gin.Engine {
	configConfig := config.NewConfig()
	postgresPostgres := postgres.NewOrGetSingleton(configConfig)
	translationRepository := repository.New(postgresPostgres)
	googleTranslator := googleapi.New()
	translationUseCase := application.NewWithDependencies(translationRepository, googleTranslator)
	loggerLogger := logger.New(configConfig)
	translator := openapi.NewTranslator(translationUseCase, loggerLogger)
	engine := openapi.NewRouter(translator)
	return engine
}

func InitializeNewHttpServer() *httpserver.Server {
	configConfig := config.NewConfig()
	postgresPostgres := postgres.NewOrGetSingleton(configConfig)
	translationRepository := repository.New(postgresPostgres)
	googleTranslator := googleapi.New()
	translationUseCase := application.NewWithDependencies(translationRepository, googleTranslator)
	loggerLogger := logger.New(configConfig)
	translator := openapi.NewTranslator(translationUseCase, loggerLogger)
	engine := openapi.NewRouter(translator)
	httpserverServer := httpserver.New(configConfig, engine)
	return httpserverServer
}

// wire.go:

var deps = []interface{}{}

var providerSet wire.ProviderSet = wire.NewSet(postgres.NewOrGetSingleton, repository.New, googleapi.New, logger.New, amqprpc.NewRouter, server.New, httpserver.New, openapi.NewTranslator, openapi.NewRouter, application.NewWithDependencies, wire.Bind(new(ports.TranslationRepository), new(*repository.TranslationRepository)), wire.Bind(new(service.Translator), new(*googleapi.GoogleTranslator)))

var providerSetSystemTests wire.ProviderSet = wire.NewSet(postgres.NewOrGetSingleton, application.NewWithDependencies, logger.New, amqprpc.NewRouter, server.New, httpserver.New, openapi.NewTranslator, openapi.NewRouter)
